name: Bug Report
description: Something is broken, crashes, or doesn't work as expected
title: "[BUG] "
labels: ["bug", "forge-queue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        *Something broke - let's fix it*

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug
      placeholder: "Game crashes when entering Chapter 3"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "Blocker - Can't continue playing"
        - "Critical - Major feature broken"
        - "Major - Significant issue but playable"
        - "Minor - Small issue, workaround exists"
        - "Trivial - Cosmetic only"
    validations:
      required: true

  - type: dropdown
    id: product
    attributes:
      label: Product
      options:
        - SpellEngine / Dread Citadel
        - HashChampions
        - PatternForge CLI
        - hashtopia.org
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Where did it happen?
      placeholder: "Chapter 3 - Vault Door encounter"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we make this happen?
      placeholder: |
        1. Start the game
        2. Load save file
        3. Enter Chapter 3
        4. Click on the vault door
        5. Crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "The vault door puzzle should appear"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "Game freezes and then crashes to desktop"
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot / Error Message
      description: Paste screenshot or error text
    validations:
      required: false

  - type: input
    id: build
    attributes:
      label: Build Version
      placeholder: v1.0-alpha
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: "macOS 14.2 / Windows 11 / Linux"
    validations:
      required: true

  - type: input
    id: reporter
    attributes:
      label: Reporter
      placeholder: Your name
    validations:
      required: true
